# Project routes - create your own routes in this file
# if method attribute is not set, the GET method is choose by default

### Example ###
#route_name:
# url: "/url"
# controller: "test" -> for testController
# method: "post" -> get by default if not set
# action: "test" -> for testAction
# module: "test" -> in module test
# with:
#   paramname: paramtype (int or string) (ex: name: "string")

# index page
index:
 url: "/"
 controller: "front"
 action: "index"

# test page
test:
 url: "/test"
 controller: "front"
 action: "test"
