# Project routes
# if method attribute is not set, the GET method is choose by default

# index page
- url: "/"
  controller: "front"
  action: "index"

# create entity with doctrine
- url: "/entity-create"
  controller: "back"
  action: "createEntity"

- url: "/entity-create"
  controller: "back"
  method: "post"
  action: "createEntity"

# test page
- url: "/test"
  controller: "front"
  action: "test"